name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build application
      run: npm run build
      env:
        # Mock environment variables for build
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
        NEXT_PUBLIC_GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        
    - name: Set Heroku Config Vars
      run: |
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
        
        # Set environment variables
        heroku config:set NODE_ENV=production --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set MONGODB_URI="${{ secrets.MONGODB_URI }}" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set CLAUDE_API_KEY="${{ secrets.CLAUDE_API_KEY }}" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set CLAUDE_MODEL="claude-3-5-haiku-20241022" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set CLAUDE_MAX_TOKENS="1000" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set GOOGLE_PLACES_API_KEY="${{ secrets.GOOGLE_PLACES_API_KEY }}" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set GOOGLE_MAPS_API_KEY="${{ secrets.GOOGLE_PLACES_API_KEY }}" --app ${{ secrets.HEROKU_APP_NAME }}
        heroku config:set NEXT_PUBLIC_GOOGLE_PLACES_API_KEY="${{ secrets.GOOGLE_PLACES_API_KEY }}" --app ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        
    - name: Verify Deployment
      run: |
        echo "🎉 Deployment completed!"
        echo "🌐 App URL: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com"
        
        # Wait for app to be ready
        sleep 30
        
        # Health check
        curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api/health/claude || echo "Health check failed"
